/*
 * TestForm.java
 *
 * Created on April 12, 2007, 12:54 PM
 */

package net.java.nboglpack.visualdesigner.tests;

import java.awt.Graphics;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.UIManager;

/**
 *
 * @author  Samuel Sperling
 */
public class TestForm extends javax.swing.JFrame {
    
    /** Creates new form TestForm */
    public TestForm() {

        
        initComponents();
        TestNode node = new TestNode();
        node.setVisible(true);
        node.setBounds(10, 10, 100, 200);
        node.addMouseListener(new MouseListener() {
            public void mouseClicked(MouseEvent e) {
            }
            public void mouseEntered(MouseEvent e) {
            }
            public void mouseExited(MouseEvent e) {
            }
            public void mousePressed(MouseEvent e) {
                nodeMousePressed(e);
            }
            public void mouseReleased(MouseEvent e) {
                nodeMouseReleased(e);
            }
        });
        this.getContentPane().add(node);
        
        refreshThread = new Thread(new Runnable() {
            public void run() {
                refresh();
            }
        }, "Refresh Thread");
        refreshThread.start();
    }
    
    public void refresh() {
        while (true) {
            
            // Do refreshings
            refreshDragingPosition();
            
            // sleep for a while
            try {
                Thread.sleep(50);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
                break;
            }
        }
    }
    
    private TestNode currentNode = null;
    private Point lastPosition;
    private Thread refreshThread;
    
    public void nodeMousePressed(MouseEvent e) {
        currentNode = (TestNode) e.getSource();
        lastPosition = this.getMousePosition();
        
    }
    public void nodeMouseReleased(MouseEvent e) {
        refreshDragingPosition();
        currentNode = null;
    }
    
    private void refreshDragingPosition() {
        if (currentNode == null) return;
        Rectangle absolutePos = currentNode.getBounds();
        Point newPosition = this.getMousePosition();
        if (newPosition == null) return;
        
        absolutePos.x += (newPosition.x - lastPosition.x) * 0.5;
        absolutePos.y += (newPosition.y - lastPosition.y) * 0.5;
        currentNode.setBounds(absolutePos);
        
        lastPosition.x += (newPosition.x - lastPosition.x) * 0.5;
        lastPosition.y += (newPosition.y - lastPosition.y) * 0.5;
//        lastPosition = newPosition;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem2.setText("Item");
        jPopupMenu1.add(jMenuItem2);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setResizeWeight(0.5);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel4.add(jCheckBox1, java.awt.BorderLayout.CENTER);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.WEST);

        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3, java.awt.BorderLayout.NORTH);

        jScrollPane4.setViewportView(jEditorPane1);

        jPanel4.add(jScrollPane4, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("tab2", jPanel4);

        jSplitPane2.setLeftComponent(jPanel7);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(jPanel8);

        jSplitPane2.setRightComponent(jScrollPane2);

        jScrollPane1.setViewportView(jSplitPane2);

        jTabbedPane1.addTab("tab2", jScrollPane1);

        jPanel1.add(jTabbedPane1);

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel2.add(jPanel3);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Test"));
        jLabel1.setText("jLabel1");
        jPanel5.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel5.add(jComboBox1);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(null);

        jPanel2.add(jPanel6);

        jLabel2.setText("lsodfnsjfs");
        jPanel2.add(jLabel2);

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1);

        jMenu1.setText("File");
        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenu1.add(jSeparator1);

        jMenu2.setText("Menu");
        jMenuItem3.setText("Item");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Item");
        jMenu2.add(jMenuItem4);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int a = 0;
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
    int a = 0;
    }//GEN-LAST:event_formPropertyChange
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        String systemLFClassName = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(systemLFClassName);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestForm().setVisible(true);
            }
        });
    }
    
    public void paintComponents(Graphics g) {
        super.paintComponents(g);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
